pipeline {
    agent any
    environment {
        ECR_REPOSITORY = credentials('ECR_REPOSITORY')
        AWS_ACCOUNT_ID = credentials('AWS_ACCOUNT_ID')
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        REGION = "ca-central-1"
    }

    stages {
        stage('Continuous Integration') {
            steps {
                script {
                    echo "linting repo"
                    echo "running unit tests"
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    echo "ECR_REPOSITORY = ${ECR_REPOSITORY}"
                    sh "docker build -t ${ECR_REPOSITORY}:latest ."
                }
            }
        }

        stage('log in to ecr') {
            steps {
                script {
                    sh 'aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ca-central-1.amazonaws.com'
                }
            }
        }

        stage('push image'){
            steps {
                script {
                    echo "Pushing image to ${ECR_REPOSITORY}:latest"
                    sh "docker push ${ECR_REPOSITORY}:latest"
                }
            }
        }

        stage('Continuous Deployment') {
            steps {
                sshagent(['ssh_key']) {
                    sh "ssh -o StrictHostKeyChecking=no ubuntu 16.54.5.238 'cd /home/ubuntu/ && wget https://raw.githubusercontent.com/entbappy/Chest-Disease-Classification-from-Chest-CT-Scan-Image/main/docker-compose.yml && export IMAGE_NAME=${ECR_REPOSITORY}:latest && aws ecr get-login-password --region ca-central-1 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.ca-central-1.amazonaws.com && docker compose up -d '"
                }
            }
        }
    }
}